version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pos_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "55432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./pos_system_schema.sql:/docker-entrypoint-initdb.d/pos_system_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./back-end
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_NAME: pos_system
    ports:
      - "9900:9900"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./front-end
    ports:
      - "5000:5000"
    depends_on:
      - backend

volumes:
  db-data:
